ARG AUTHOR
FROM ghcr.io/${AUTHOR}:ubuntu-base

# Run everything as root
USER root

# Install go
RUN curl -L "https://dl.google.com/go/go1.18.3.linux-$(dpkg --print-architecture).tar.gz" | tar -C /usr/local -xzvf -

# Setup go env vars
ENV GOROOT /usr/local/go
ENV PATH $PATH:$GOROOT/bin

ENV GOPATH /home/coder/go
ENV GOBIN $GOPATH/bin
ENV PATH $PATH:$GOBIN

# Set back to coder user
USER coder
