ARG AUTHOR
FROM ghcr.io/${AUTHOR}:ubuntu-base

# Run everything as root
USER root

# Install jupyter
RUN pip3 install jupyter-core==4.7.1 && \
    pip3 install jupyterlab

# Set back to coder user
USER coder
